exclude: (^\.pixi/|.snap)
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: pixi run -e lint ruff check --fix --exit-non-zero-on-fix --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: pixi run -e lint ruff format --force-exclude
        language: system
        types_or: [python]
        require_serial: true
      - id: typos
        name: typos
        entry: pixi run -e lint typos --write-changes --force-exclude
        language: system
        types: [text] 