[project]
name = "flow_imitation"
requires-python = ">= 3.8"
version = "0.1.0"
description = "Flow and diffusion-based policies for robotic imitation learning"
authors = [
    {name = "Tatsuya Kamijo"}
]
dependencies = ["robomimic==0.2.0", "opencv-python==4.6.0.66", "thop==0.1.1.post2209072238", "robosuite==1.4.0", "bddl==1.0.1", "gym==0.25.2"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["pytorch", "conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
flow_imitation = { path = ".", editable = true }

[tool.pixi.dependencies]
python = "==3.8.13"
pytorch = {version = "==1.11.0", channel = "pytorch"}
torchvision = {version = "==0.12.0", channel = "pytorch"}  
torchaudio = {version = "==0.11.0", channel = "pytorch"}
cudatoolkit = "11.3.*"
numpy = "==1.22.4"
scipy = "*"
matplotlib = "==3.5.3"
pandas = "*"
scikit-learn = "*"
pillow = "*"
jupyter = "*"
ipython = "*"
tqdm = "*"
transformers = "==4.21.1"
einops = "==0.4.1"
timm = "*"
hydra-core = "==1.2.0"
omegaconf = "*"
wandb = "==0.13.1"
tensorboard = "*"
future = "==0.18.2"
cloudpickle = "==2.1.0"
easydict = "==1.9"

[tool.pixi.tasks]
