policy:
  type: "diffusion"
  n_obs_steps: 2
  horizon: 16
  n_action_steps: 8
  repo_id: "lerobot/pusht"
  push_to_hub: false

dataset:
  repo_id: "lerobot/pusht"

batch_size: 64
log_freq: 50
save_freq: 1000
steps: 100000
job_name: "dp_pusht"

wandb:
  enable: "true"
  project: "flow_diffusion_pusht"