policy:
  type: "flow"
  n_obs_steps: 2
  horizon: 16
  n_action_steps: 8
  repo_id: "lerobot/pusht"

dataset:
  repo_id: "lerobot/pusht"

batch_size: 64
log_freq: 50
save_freq: 1000
steps: 100000
job_name: "flow_pusht"

wandb:
  enable: "false"
  project: "flow_pusht"
